name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy Code via SFTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          echo "Starting SFTP deployment..."
          lftp -c "
            open -u \"$FTP_USER\",\"$FTP_PASSWORD\" sftp://$FTP_HOST:$FTP_PORT;
            mirror -R --delete --exclude .git/ --exclude .github/ ./ $DEPLOY_PATH
          "
          echo "✅ Deploy finished successfully."

      - name: Notify Deployment Completion to GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENS }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          echo "Starting to create issue comment..."
          response=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"**✅ Berhasil Deploy ke Development Server (SFTP)**:\\n- **Branch**: main\\n- **Last Commit**: $SHA\\n- **Server Path**: \`$DEPLOY_PATH\`\\n\\nSilakan cek hasil di server.\"}" \
            https://api.github.com/repos/$REPO/issues/1/comments)
          echo "API response from comment creation: $response"

          echo "Starting to assign assignee..."
          assign_response=$(curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"assignees\": [\"alfianharisusatya\"]}" \
            https://api.github.com/repos/$REPO/issues/1)
          echo "API response from assignee assignment: $assign_response"